name: Build packages

on:
  push: 
    branches:
      - main
  pull_request:

jobs:
  windows-msvc:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build getopt
        shell: cmd
        run: |
          msbuild getopt.sln /p:Configuration=Debug /p:Platform=Win32
          msbuild getopt.sln /p:Configuration=Debug /p:Platform=x64
          msbuild getopt.sln /p:Configuration=Release /p:Platform=Win32
          msbuild getopt.sln /p:Configuration=Release /p:Platform=x64

  windows-conan:
    runs-on: windows-2025
    strategy:
      matrix:
        profile: [ windows-clang, windows-msvc ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Conan
        run: |
          pip install conan==2.18.1
          conan --version
      - name: Build getopt
        shell: cmd
        run: |
          conan create . --profile:a=${{ matrix.profile }}
      - name: Upload Conan packages to Cloudsmith
        run: |
          conan remote add cloudsmith https://conan.cloudsmith.io/qmfrederik/gnustep/
          conan remote login -p ${{ secrets.CLOUDSMITH_API_KEY }} cloudsmith ${{ secrets.CLOUDSMITH_USER }}
          conan upload getopt/* --confirm -r cloudsmith
        if: ${{ github.ref == 'refs/heads/master' }}
